[package]
name = "basic"
version = "0.1.0"
authors = ["Mike Tang <miketang84@outlook.com>"]

[dependencies]
sapper = { git="https://github.com/sappworks/sapper" }
sapper_query = { path="../../" }
log = "*"
env_logger = "*"


